import { Metadata } from "next";
import classes from "./home.module.scss";

async function fetchUsers() {
  const response = await fetch("https://jsonplaceholder.typicode.com/users"); // 예시 API URL
  if (!response.ok) {
    throw new Error("Network response was not ok");
  }
  return response.json();
}

//메타 데이터
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function Home() {
  const awiat = await fetchUsers();
  console.log(awiat);
  return (
    <main>
      <h1 className={classes.title}>무한한 아름다움, 무제한 무료 응답</h1>
    </main>
  );
}
